apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: party-battle-backend-v2-22-0
  labels:
    app: party-battle-backend-v2-22-0

spec:
  replicas: 1
  selector:
    matchLabels:
      app: party-battle-backend-v2-22-0
  template:
    metadata:
      labels:
        app: party-battle-backend-v2-22-0
    spec:
      containers:
        - name: party-battle-backend
          image: ghcr.io/thirty-degrees/backend-party-battle:70ab9ff706e23b9fd0c486db0cb80494e98d1fbf
          ports:
            - name: api
              containerPort: 2567
      imagePullSecrets:
        - name: ghcr-secret
