apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: thirty-degrees-homepage
  labels:
    app: thirty-degrees-homepage

spec:
  replicas: 1
  selector:
    matchLabels:
      app: thirty-degrees-homepage
  template:
    metadata:
      labels:
        app: thirty-degrees-homepage
    spec:
      containers:
        - name: thirty-degrees-homepage
          image: ghcr.io/thirty-degrees/homepage:abea7e94b15e331ce4d36e0372fa416869641782
          ports:
            - name: web
              containerPort: 3000 
      imagePullSecrets:
        - name: ghcr-secret