apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: party-battle-frontend
  labels:
    app: party-battle-frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: party-battle-frontend
      app.kubernetes.io/part-of: party-battle
  template:
    metadata:
      labels:
        app: party-battle-frontend
        app.kubernetes.io/part-of: party-battle
    spec:
      containers:
        - name: party-battle-frontend
          image: ghcr.io/thirty-degrees/frontend-party-battle-web:70ab9ff706e23b9fd0c486db0cb80494e98d1fbf
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret


