apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: watermark-webapp
  labels:
    app: watermark-webapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: watermark-webapp
  template:
    metadata:
      labels:
        app: watermark-webapp
    spec:
      containers:
        - name: watermark-webapp
          image: ghcr.io/thirty-degrees/watermark-webapp:5bed8c6007c633ef6ec90e432917e14fce6d5179
          ports:
            - name: web
              containerPort: 3000 
      imagePullSecrets:
        - name: ghcr-secret